### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by ghost** [ObelusFamily/Anythink-Market-aivh4nhc#1]
It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data. Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by DeBaFig** [comment]
![image](https://user-images.githubusercontent.com/46844031/202875351-cfa74f70-29de-481a-bf4e-0536d35d47c3.png)

Bugfixed img default now working
